steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/chat:$REVISION_ID', '.' ]
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/websocket', 'websocket=gcr.io/$PROJECT_ID/chat:$REVISION_ID']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=chat'
#- name: 'gcr.io/cloud-builders/npm'
#  args: ['install', 'slack', 'node-env-file']
#- name: 'gcr.io/cloud-builders/npm'
#  args: ['run', 'slack-build']
images:
- 'gcr.io/$PROJECT_ID/chat:$REVISION_ID'